styles:
  BO 1/1:
    size: 12
    width: 1140
  BO 1/2:
    size: 6
    width: 570
  BO 1/3:
    size: 4
    width: 380
  BO 1/4:
    size: 3
    width: 285
  BO 3/4:
    size: 9
    width: 855
  BO 2/3:
    size: 8
    width: 760

