<?php

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormState;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_install().
 */
function bo_webform_uninstall() {
  // Delete all bo entities of bundle 'webform'.
  $storage_handler = \Drupal::entityTypeManager()
    ->getStorage('bo');
  $nodes = $storage_handler->loadByProperties(['bundle' => 'webform']);
  $storage_handler->delete($nodes);
}


/**
 * @param array $vars
 */
function bo_webform_preprocess_views_view_field_bo(array &$vars) {
  $renderer = \Drupal::service('renderer');

  foreach ($vars['bo'] as $delta => $element) {
    if ($element['entity_type'] == 'webform') {
      $form = [
        '#lazy_builder' => [
          '\Drupal\bo_webform\WebformLazyBuilder::buildWebform',
          [
            $vars['bo'][$delta]['target_id'],
          ],
          '#create_placeholder' => TRUE,
        ]
      ];
      $vars['bo'][$delta]['rendered']['form'] = $renderer->render($form);
    }
  }

  $administer_entities = \Drupal::currentUser()->hasPermission("show twig help");
  if ($administer_entities) {
    /** @var \Drupal\bo\Service\BoHelp $boHelp */
    $boHelp = \Drupal::service('bo.help');
    /** @var \Drupal\bo\Entity\BoEntity $entity */
    $entity = $vars['row']->_entity;
    $vars['#attached']['drupalSettings']['bo'][$entity->id()] = $boHelp->renderHelp($vars['bo']);
  }
}
